name: Check

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python env
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        check-latest: true

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Checkout extism/cli
      uses: actions/checkout@v3
      with:
        repository: extism/cli
        path: cli

    - name: Install Extism & CLI
      run: |
        pushd cli
        pip3 install cffi
        pip3 install .
        popd

        extism install git

    - name: make
      run: make

    - name: make check
      run: make check
